name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci

      - run: npm run dist

      - id: run-ts
        name: Run for .ts files
        uses: ./
        with:
          base-branch: master
          extensions: .ts

      - id: run-json
        name: Run for .json files
        uses: ./
        with:
          # Don't provide the base-branch here. Default should be master.
          extensions: .json

      - name: Print results
        run: echo "${{ steps.run-ts.outputs.files }}"

      - run: npm test

      - name: ESLint everything
        run: npx eslint src/**/**.ts __tests__/**/**.ts

      - uses: harveyr/gh-action-publish@releases/v0
        with:
          dirs: dist
        if: contains(github.ref, 'refs/heads/versions/' )
