name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci

      - run: npm run dist

      - id: run-api
        name: Run with API
        uses: ./
        with:
          base-branch: master
          extensions: .ts
          use-api: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - id: run-ts
        name: Run for .ts files
        uses: ./
        with:
          base-branch: master
          extensions: .ts

      - name: Print .ts results
        run: echo "${{ steps.run-ts.outputs.files }}"

      # This second run serves not only to test different output, but also the
      # logic that determines whether we do an unshallow pull. We should do that
      # pull only on the first run--not on the second.
      - id: run-json
        name: Run for .json files
        uses: ./
        with:
          # Don't provide the base-branch here. Default should be master.
          extensions: .json

      - name: Print .json results
        run: echo "${{ steps.run-json.outputs.files }}"

      - run: npm test

      - name: ESLint everything
        run: npx eslint src/**/**.ts __tests__/**/**.ts

      - uses: harveyr/gh-action-publish@releases/v0
        with:
          dirs: dist
        if: contains(github.ref, 'refs/heads/versions/' )
