name: CI
on: [push]
jobs:
  # Build with old actions/checkout version
  build-legacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm run dist

      - id: run
        uses: ./
        with:
          base-branch: master
          extensions: .ts

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci

      - run: npm run build

      - run: npm test

      - name: ESLint everything
        run: npx eslint src/**.ts

      - run: npm run dist

      - id: run
        uses: ./
        with:
          base-branch: origin/master
          extensions: .ts

      - name: Print results
        run: echo "${{ steps.run.outputs.files }}"

      - uses: harveyr/gh-action-publish@releases/v0
        with:
          dirs: dist
        if: contains(github.ref, 'refs/heads/versions/' )
