name: "Test typescript-action"
on: [push]
  # pull_request:
  # push:
  #   branches:
  #     - master
  #     - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
    # - run: npm test
    - uses: ./
      with:
        base-branch: master
        extensions: .ts
