name: "Test typescript-action"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        version: 12.x

    - run: npm ci

    - run: npm run build

    - run: npm test

    - id: run
      uses: ./
      with:
        base-branch: master
        extensions: .ts

    - name: Print results
      run: echo "${{ steps.run.outputs.files }}"

    # Test an example use case of this action
    - name: ESLint changed files
      run: npx eslint "${{ steps.run.outputs.files }}"
      if: steps.run.outputs.files

    # Double check that _everything_ looks good
    - name: ESLint everything
      run: npx eslint src/**.ts


